modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/ImprovedMobs/issues"
[[mods]]
modId="improvedmobs"
version="${version}"
displayName="Improved Mobs Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/improved-mobs"
logoFile="icon.png"
authors="Flemmli97"
description='''Improved AI and customizations for mobs.'''
[[dependencies.improvedmobs]]
modId="minecraft"
mandatory=true
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.improvedmobs]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.improvedmobs]]
modId="tenshilib"
mandatory=true
versionRange="[${tenshilib_version},)"
ordering="NONE"
side="BOTH"
