modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/ImprovedMobs/issues"
[[mods]]
modId="improvedmobs"
version="${version}"
displayName="Improved Mobs Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/improved-mobs"
logoFile="icon.png"
authors="Flemmli97"
description='''Improved AI and customizations for mobs.'''
[[dependencies.improvedmobs]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.improvedmobs]]
modId="forge"
mandatory=true
versionRange="[45.0.22,)"
ordering="NONE"
side="BOTH"
[[dependencies.improvedmobs]]
modId="tenshilib"
mandatory=true
versionRange="[1.19.4-1.6.15,)"
ordering="NONE"
side="BOTH"
