modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/ImprovedMobs/issues"
[[mods]]
modId="improvedmobs"
version="${version}"
displayName="Improved Mobs Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/improved-mobs"
logoFile="icon.png"
authors="Flemmli97"
description='''Improved AI and customizations for mobs.'''
[[dependencies.improvedmobs]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"
[[dependencies.mobbattle]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.improvedmobs]]
modId="tenshilib"
mandatory=true
versionRange="[1.19-1.6.9,)"
ordering="NONE"
side="BOTH"
